name: Build Telegram Sender App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Android Code
      uses: actions/checkout@v4  # تم التحديث هنا إلى v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4 # تم التحديث هنا إلى v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4 # تم التحديث هنا إلى v4
      with:
        name: Hussain-App-Ready
        path: app/build/outputs/apk/debug/app-debug.apk
